---
title: "0000_data_cleaning"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, eval = T, echo =F}
.libPaths( c( "~/R_LIBS" , .libPaths() ) )
setwd("~/Desktop/nba_data")
```

```{r, eval = T, message=F, warning=F}
library(data.table)
library(Rcpp)
library(RcppArmadillo)
library(farver)
library(ggplot2)
library(mvtnorm)
library(dplyr)
library(reshape2)
library(plot3D)
library(Matrix)
library(superheat)
library(mcclust)
library(RCurl)
library(jsonlite)
library(sp)
library(zoo)
library(lubridate)
library(stringr)
library(gridExtra)
library(grid)
library(RColorBrewer)
library(ggrepel)
library(viridis)
library(tidyr)
library(gifski)
library(transformr)
library(gganimate)
library(pracma)
library(scales)

```

```{r, eval = T, message=F, warning=F}
#Rcpp::sourceCpp("./Code/Hidalgo_Code.cpp")
source("./Code/Helpers_Code.R")
source('./Code/plot functions.R')
```
## Clean Main Dataset

```{r, eval = T}

# Plot an individual play

allm <- readRDS("CLEatGSW.RDS") 

allm$descrip <-ifelse(!is.na(allm$HOMEDESCRIPTION), as.character(allm$HOMEDESCRIPTION), as.character(allm$VISITORDESCRIPTION)) 

allm <- dplyr::filter(allm, (EVENTMSGTYPE %in% c(1,2)) & (word(descrip, 2) != "BLOCK")) 

allm$y_loc <- as.numeric(as.character(allm$y_loc))
allm$shot_clock <- as.numeric(as.character(allm$shot_clock))
allm$radius <- as.numeric(as.character(allm$radius))
allm$quarter <- as.character(allm$quarter)

allm <- allm %>%
        mutate(lastname_clean = case_when(lastname == "ball" ~ "ball",
                                          team == "home" ~ paste0(lastname, "_home"),
                                          TRUE ~ paste0(lastname, "_away"))) %>%
        group_by(shot_clock, event.id, team, lastname) %>%
        filter(x_loc == max(x_loc)) %>%
        ungroup()

# Get Home vs Away Players
home_players <- allm %>%
                filter(team == "home") %>%
                subset(select = c(lastname_clean))

home_players <- unique(home_players)

away_players <- unique(allm %>%
                       filter(team == "away") %>%
                       subset(select = lastname_clean))

away_players <- unique(away_players)

score_locations <- data.frame()

# Get the location of a shot
get_scored_location <- function(i) {
  
    play_id <- unique_events[i,]$event.id
    
    play <- allm %>%
        filter((event.id == play_id) & !is.na(shot_clock))
    
    play <- play[order(play$lastname_clean, play$shot_clock),]
    
    play <- play %>%
            filter(shot_clock < 23)

    # Plot ball radius 
    ball_play <- play %>%
                 filter((lastname == "ball"))
 
    ball_plot <- ball_play %>%
                 ggplot(aes(x = 24-shot_clock, y=radius, group=lastname_clean, colour=lastname_clean)) +
                 geom_line() +
                 theme_bw() +
                 xlab("Play Time (seconds)") +
                 ylab("Ball Height (feet)") +
                 labs(colour = "Ball")
    
    
    plot(ball_plot)
    ggsave(paste0("play_", play_id, "_ball_z_location.jpg"))
    
    # To get where a shot was taken from, we will follow a 3 step process
    # 1) Find all peaks over 10ft in the dataset
    # 2) Find the corresponding minima just before the peak. This represents where the shot was taken from
    # 3) Use these datapoints to generate a shot chart
    
    peaks <- ball_play %>%
             filter((radius > 10) & (radius > lag(radius)) & (radius > lead(radius))) 
    
    if (is.na(peaks[1,]$event.id)) {
        return("Size of peaks is missing")
    }
    
    peaks2 <- peaks %>%
              filter(datetime2 == max(datetime2))
    
    troughs <- ball_play %>%
               filter((radius < lag(radius)) & (radius > lead(radius)) & (datetime2 < peaks2$datetime2) & (radius < 10))
    
    if (is.na(troughs[1,]$event.id)) {
        return("Size of troughs is missing")
    }
    
    # This is where the player took their shot
    troughs2 <- troughs %>%
                filter(datetime2 == max(datetime2)) %>%
                subset(select = c(event.id, x_loc, y_loc, radius, shot_clock, game_clock, quarter, datetime2))
    
    angle <- atan2((peaks2$radius - troughs2$radius), sqrt((peaks2$x_loc - troughs2$x_loc)^2 + (peaks2$y_loc - troughs2$y_loc)^2))
    
    play_info <- unique_events %>%
                 # ignore blocks for now, just want strictly misses and makes
                 filter((word(descrip, 2) != "BLOCK") & (event.id == play_id)) %>%
                 mutate(miss = case_when(word(descrip, 1) == "MISS" ~ 1,
                                         TRUE ~ 0),
                        player_involved = case_when(miss == 0 ~ paste0(word(descrip, 1), "_", ball_possession),
                                                    TRUE ~ paste0(word(descrip, 2), "_", ball_possession)),
                        scored_on_play_character = case_when(scored_on_play == 1 ~ "Yes",
                                                             TRUE ~ "No")) %>%
                 subset(select = c(event.id, ball_possession, descrip, player_involved, SCORE, scored_on_play, scored_on_play_character, miss, home_score, away_score))
    
    # Add who the player was that took the shot
    shot_position <- merge(troughs2, play_info, by="event.id")
    
    # Get distance of all players from each other 
    
    distance_of_players <- play %>%
                           subset(select = c(lastname_clean, lastname, event.id, datetime2, shot_clock, x_loc, y_loc)) %>%
                           gather(key="position", value="coords", x_loc:y_loc) %>%
                           mutate(shooting_player = case_when(lastname_clean == shot_position$player_involved ~ 1,
                                                              TRUE ~ 0),
                                  shooting_player_status = case_when(shot_position$player_involved %in% c(home_players$lastname_clean) ~ "home",
                                                                     TRUE ~"away"),
                                  player_status = case_when(lastname %in% c(home_players$lastname_clean) ~ "home",
                                                            TRUE ~ "away"),
                                  attack_defend_flag = case_when(lastname == "ball" ~ "a",
                                                                 shooting_player_status == player_status ~ "a", # attacking
                                                                 TRUE ~ "d"),
                                  lastname2 = case_when(shooting_player == 1 ~ "1_Shooter",
                                                        TRUE ~ lastname_clean),
                                  player_pos = paste0(attack_defend_flag, "_", lastname2, "_", substr(position, 1,1))) %>%
                           arrange(player_pos, shot_clock, datetime2, event.id) %>%
                           subset(select = c(player_pos, event.id, datetime2, shot_clock, coords)) %>%
                           spread(player_pos, coords) 
    
    colnames(distance_of_players) <- c("event.id", "datetime2", "shot_clock", "shooter_x", "shooter_y", "ball_x", "ball_y",
                                       "a2_x", "a2_y", "a3_x", "a3_y", "a4_x", "a4_y", "a5_x", "a5_y",
                                       "d1_x", "d1_y", "d2_x", "d2_y", "d3_x", "d3_y", "d4_x", "d4_y", "d5_x", "d5_y")
    
    
    distance_of_players <- distance_of_players %>%
                           mutate(seconds_elapsed = as.numeric(abs(shot_clock - lag(shot_clock))),
                                  # Player velocities
                                  ball_velocity = sqrt((ball_x-lag(ball_x))^2 + (ball_y-lag(ball_y))^2)/seconds_elapsed,
                                  shooter_velocity = sqrt((shooter_x-lag(shooter_x))^2 + (shooter_y-lag(shooter_y))^2)/seconds_elapsed,
                                  a2_velocity = sqrt((a2_x-lag(a2_x))^2 + (a2_y-lag(a2_y))^2)/seconds_elapsed,
                                  a3_velocity = sqrt((a3_x-lag(a3_x))^2 + (a3_y-lag(a3_y))^2)/seconds_elapsed,
                                  a4_velocity = sqrt((a4_x-lag(a4_x))^2 + (a4_y-lag(a4_y))^2)/seconds_elapsed,
                                  a5_velocity = sqrt((a5_x-lag(a5_x))^2 + (a5_y-lag(a5_y))^2)/seconds_elapsed,
                                  d1_velocity = sqrt((d1_x-lag(d1_x))^2 + (d1_y-lag(d1_y))^2)/seconds_elapsed,
                                  d2_velocity = sqrt((d2_x-lag(d2_x))^2 + (d2_y-lag(d2_y))^2)/seconds_elapsed,
                                  d3_velocity = sqrt((d3_x-lag(d3_x))^2 + (d3_y-lag(d3_y))^2)/seconds_elapsed,
                                  d4_velocity = sqrt((d4_x-lag(d4_x))^2 + (d4_y-lag(d4_y))^2)/seconds_elapsed,
                                  d5_velocity = sqrt((d5_x-lag(d5_x))^2 + (d5_y-lag(d5_y))^2)/seconds_elapsed,
                                  # Get distance of shooter from each player 
                                  distance_shooter_ball = sqrt((shooter_x-ball_x)^2 + (shooter_y-ball_y)^2),
                                  distance_shooter_a2 = sqrt((shooter_x-a2_x)^2 + (shooter_y-a2_y)^2),
                                  distance_shooter_a3 = sqrt((shooter_x-a3_x)^2 + (shooter_y-a3_y)^2),
                                  distance_shooter_a4 = sqrt((shooter_x-a4_x)^2 + (shooter_y-a4_y)^2),
                                  distance_shooter_a5 = sqrt((shooter_x-a5_x)^2 + (shooter_y-a5_y)^2),
                                  distance_shooter_d1 = sqrt((shooter_x-d1_x)^2 + (shooter_y-d1_y)^2),
                                  distance_shooter_d2 = sqrt((shooter_x-d2_x)^2 + (shooter_y-d2_y)^2),
                                  distance_shooter_d3 = sqrt((shooter_x-d3_x)^2 + (shooter_y-d3_y)^2),
                                  distance_shooter_d4 = sqrt((shooter_x-d4_x)^2 + (shooter_y-d4_y)^2),
                                  distance_shooter_d5 = sqrt((shooter_x-d5_x)^2 + (shooter_y-d5_y)^2),
                                  # Get velocity of other players as they approach shooter
                                  velocity_shooter_ball = (distance_shooter_ball - lag(distance_shooter_ball)) / seconds_elapsed,
                                  velocity_shooter_a2 = (distance_shooter_a2 - lag(distance_shooter_a2)) / seconds_elapsed,
                                  velocity_shooter_a3 = (distance_shooter_a3 - lag(distance_shooter_a3)) / seconds_elapsed,
                                  velocity_shooter_a4 = (distance_shooter_a4 - lag(distance_shooter_a4)) / seconds_elapsed,
                                  velocity_shooter_a5 = (distance_shooter_a5 - lag(distance_shooter_a5)) / seconds_elapsed,
                                  velocity_shooter_d1 = (distance_shooter_d1 - lag(distance_shooter_d1)) / seconds_elapsed,
                                  velocity_shooter_d2 = (distance_shooter_d2 - lag(distance_shooter_d2)) / seconds_elapsed,
                                  velocity_shooter_d3 = (distance_shooter_d3 - lag(distance_shooter_d3)) / seconds_elapsed,
                                  velocity_shooter_d4 = (distance_shooter_d4 - lag(distance_shooter_d4)) / seconds_elapsed,
                                  velocity_shooter_d5 = (distance_shooter_d5 - lag(distance_shooter_d5)) / seconds_elapsed,
                                  # Statistics over the course of the play
                                  avg_distance_shooter_ball = mean(distance_shooter_ball),
                                  avg_distance_shooter_a2 = mean(distance_shooter_a2),
                                  avg_distance_shooter_a3 = mean(distance_shooter_a3),
                                  avg_distance_shooter_a4 = mean(distance_shooter_a4),
                                  avg_distance_shooter_a5 = mean(distance_shooter_a5),
                                  avg_distance_shooter_d1 = mean(distance_shooter_d1),
                                  avg_distance_shooter_d2 = mean(distance_shooter_d2),
                                  avg_distance_shooter_d3 = mean(distance_shooter_d3),
                                  avg_distance_shooter_d4 = mean(distance_shooter_d4),
                                  avg_distance_shooter_d5 = mean(distance_shooter_d5),
                                  # Shot Angle
                                  shot_angle = angle) %>%
                            filter(shot_clock == shot_position$shot_clock) %>%
                            subset(select = -c(event.id, datetime2))
      
    shot_position <- merge(shot_position, distance_of_players, by="shot_clock")
    
    if (i == 1) {
        score_locations <<- shot_position
    } else {
        score_locations <<- rbind(as.data.frame(score_locations), as.data.frame(shot_position))
    }
    
    # Plot position of players when player took shot
    colp <- brewer.pal(12, "Paired")[c(1, 2,3,4,5,6,7,8, 9,10,11)]
    
    play_15 <- play %>%
               filter(datetime2 == troughs2$datetime2)
    
    play_15 <- P_180 + 
               geom_point(data = play_15, aes(x_loc, -y_loc, group = lastname, col = lastname), size = 3) + 
               geom_text() +
               scale_color_manual(values = colp) +
               theme_bw() +
               labs(colour = "Player")
    
    plot(play_15)
    ggsave(paste0("play_", play_id, "_shot_configuration_taken.jpg"))
}

for (i in 1:length(ev)) {
    get_scored_location(i)
}

```


```{r, eval = T}
# For shots, see how categories of miss and make align
library(glmnet)
library(caret)

set.seed(3456)

cleaned_data <- score_locations %>%
                filter(!(event.id %in% c(112, 131, 140, 229, 231, 306, 397, 43, 316, 318))) %>%
                subset(select = -c(event.id, datetime2, descrip, SCORE, scored_on_play_character, game_clock, player_involved, miss, home_score, away_score, ball_possession, radius, seconds_elapsed, quarter,
                                   avg_distance_shooter_ball, avg_distance_shooter_a2, avg_distance_shooter_a3, avg_distance_shooter_a4, avg_distance_shooter_a5,
                                   avg_distance_shooter_d1, avg_distance_shooter_d2, avg_distance_shooter_d3, avg_distance_shooter_d4, avg_distance_shooter_d5))

made_shots <- cleaned_data %>%
              ggplot(aes(x=scored_on_play)) +
              geom_histogram() +
              theme_bw()

plot(made_shots)

# Regress 

x <- as.matrix(cleaned_data %>%
     subset(select = -c(scored_on_play)))

y <- as.matrix(cleaned_data %>%
     subset(select = c(scored_on_play)))

split <- createDataPartition(y, p = 0.8,
                             list = FALSE,
                             times = 1)

x_train <- as.matrix(x[split,])
y_train <- as.matrix(y[split,])

x_test <- as.matrix(x[-split,])
y_test <- as.matrix(y[-split,])

cross_val <- cv.glmnet(x_train, y_train, 
                       family = 'binomial', 
                       type.measure = 'mse',
                       alpha = 1, 
                       nlambda = 100)

fit_min <- glmnet(x, y, 
              family = 'binomial', 
              alpha = 1, 
              lambda = cross_val$lambda.min)


test <- varImp(fit_min, lambda = cross_val$lambda.min)

coef(fit_min)

predictions_min <- predict(fit_min, newx = x_test, type = 'class')

F_meas(
  data = as.factor(predictions_min),
  reference = as.factor(y_test)
)

precision(  data = as.factor(predictions_min),
  reference = as.factor(y_test))

recall(  data = as.factor(predictions_min),
  reference = as.factor(y_test))

# Get average shooting percentage for all shots
shooting_perc_avg <- sum(score_locations$scored_on_play) / sum(score_locations$scored_on_play + score_locations$miss) # 36.9%


```


```{r, eval = T}
# Fit logistic regression

set.seed(3456)

cleaned_data <- score_locations %>%
                filter(!(event.id %in% c(112, 131, 140, 229, 231, 306, 397, 43, 316, 318))) %>%
                subset(select = -c(event.id, datetime2, descrip, SCORE, scored_on_play_character, game_clock, player_involved, miss, home_score, away_score, ball_possession, radius, seconds_elapsed, quarter,
                                   avg_distance_shooter_ball, avg_distance_shooter_a2, avg_distance_shooter_a3, avg_distance_shooter_a4, avg_distance_shooter_a5,
                                   avg_distance_shooter_d1, avg_distance_shooter_d2, avg_distance_shooter_d3, avg_distance_shooter_d4, avg_distance_shooter_d5))

made_shots <- cleaned_data %>%
              ggplot(aes(x=scored_on_play)) +
              geom_histogram() +
              theme_bw()

plot(made_shots)

regression <- glm(scored_on_play ~ ., data = cleaned_data, family="binomial")

regression_limited <- glm(scored_on_play ~ ball_velocity + shooter_velocity + distance_shooter_d1 + distance_shooter_d2 + distance_shooter_d3 + distance_shooter_d4 + distance_shooter_d5 + shot_angle + shot_clock, data = cleaned_data, family="binomial")



```

```{r, eval = T}

library(xgboost)
library(caret)
library(DiagrammeR)

x <- as.matrix(cleaned_data %>%
     subset(select = -c(scored_on_play)))

y <- as.matrix(cleaned_data %>%
     subset(select = c(scored_on_play)))

split <- createDataPartition(y, p = 0.8,
                             list = FALSE,
                             times = 1)

x_train <- as.matrix(x[split,])
y_train <- as.matrix(y[split,])

x_test <- as.matrix(x[-split,])
y_test <- as.matrix(y[-split,])

xgb_train <- xgb.DMatrix(data = x_train, label = y_train)
xgb_test <- xgb.DMatrix(data = x_test, label = y_test)

model <- xgb.train(data = xgb_train, max.depth = 2, nrounds = 12, eval.metric="error", eval.metric="logloss", objective="binary:logistic")

model_sumary <- xgb.dump(model, with_stats=TRUE)

xgb.plot.tree(model = model)

importance_matrix <- xgb.importance(model = model)
print(importance_matrix)


pred <- predict(model, x_test)
pred <- as.data.frame(matrix(pred, ncol=1,byrow=TRUE)) %>%
        mutate(V1 = case_when(V1 > 0.5 ~ 1,
                              TRUE ~ 0))

pred[pred$V1 > 0.5] <- 1
pred[pred$V1 <= 0.5] <- 0

precision(  data = as.factor(pred),
  reference = as.factor(y_test))

recall(  data = as.factor(pred),
  reference = as.factor(y_test))

x_tesfad <- abs(pred - y_test)

sum(x_tesfad)


```

## Clean Main Dataset

```{r, eval = T}

allm <- readRDS("CLEatGSW.RDS")
               
allm$descrip <-ifelse(!is.na(allm$HOMEDESCRIPTION), as.character(allm$HOMEDESCRIPTION), as.character(allm$VISITORDESCRIPTION)) 

allm <- dplyr::filter(allm, (EVENTMSGTYPE %in% c(1,2)) & (word(descrip, 2) != "BLOCK") & !is.na(shot_clock))

select_id <- function(all.movements = all.movements, id = id){
    e1 <- dplyr::filter(all.movements, event.id == id) 
    e1$x_loc <- as.numeric(as.character(e1$x_loc))
    e1$y_loc <- as.numeric(as.character(e1$y_loc))
    e1$shot_clock <- as.numeric(as.character(e1$shot_clock))
    e1$shot_clock2 <- round(e1$shot_clock,1)
    e1 <- dplyr::arrange(e1, datetime2)
    
     e1$ii <- 1
    e1 <- e1 %>% dplyr::mutate(act = ifelse(shot_clock2 > lag(shot_clock2), ii + 1,ii)) # need to split actions because multiple actions are mingled
    
    breaks <- c(ymd_hms('2010-01-01 00:00:00'), e1[which(e1$act == 2),]$datetime2, Sys.time())
    e1$action <- cut.POSIXt(e1$datetime2, breaks = breaks, labels = 1:(length(breaks)-1))
    
    e1 <- dplyr::filter(e1, shot_clock2 < 24)
    e1 <- e1 %>% dplyr::group_by(event.id) %>%  dplyr::mutate(ids = dplyr::row_number())
  
}

table_fixing_clock <- read.csv('across plays fixing clock issues.csv')
table_fixing_clock$quarter <- factor(table_fixing_clock$quarter)
table_fixing_clock$EVENTMSGTYPE <- factor(table_fixing_clock$EVENTMSGTYPE)

allm$EVENTMSGTYPE <- droplevels(allm$EVENTMSGTYPE)
allm$ball_possession <- factor(allm$ball_possession)

allm <- allm %>% left_join(table_fixing_clock, by = c('event.id', 'quarter', 'EVENTMSGTYPE', 'ball_possession'))

# will exclude the plays with issues according to the visualization done with assess

allm <- dplyr::filter(allm, comment != 'e')

```

## List distinct events during game
```{r, eval = T}
unique_events <- allm %>% 
                 group_by(event.id, EVENTMSGTYPE, ball_possession, quarter, descrip, SCORE) %>%
                 mutate(time_scored = min(as.numeric(as.character(game_clock)))) %>%
                 ungroup() %>%
                 dplyr::select(event.id, EVENTMSGTYPE, ball_possession, quarter, descrip, SCORE, time_scored) %>% 
                 distinct() %>%
                 mutate(scored_on_play = case_when(is.na(SCORE) ~ 0,
                                                   TRUE ~ 1),
                        away_score = as.numeric(word(SCORE, 1)),
                        home_score = as.numeric(word(SCORE, 3)),
                        time_scored = 720 - time_scored + (as.numeric(as.character(quarter)) - 1)*720) 

ev <- unique(allm$event.id) # event

game_score <- unique_events %>%
              filter(!is.na(SCORE)) %>%
              mutate(player_scored = word(descrip, 1),
                     points_scored = case_when(is.na(coalesce(lag(home_score), lag(away_score))) ~ coalesce(home_score, away_score),
                                               ball_possession == "away" ~ away_score - lag(away_score),
                                               ball_possession == "home" ~ home_score - lag(home_score),
                                               TRUE ~ 0))
ev_scored <- unique(game_score$event.id) # event

game_score_plot <- game_score %>%
                   ggplot(aes(x=time_scored)) +
                   geom_line(aes(y=home_score, colour="home")) +
                   geom_line(aes(y=away_score, colour="away"))

```

## Plot plays for a given player
```{r, eval = T}



```

## Clean main dataset further for individual play info
```{r, eval = T}
#
# calculate_play - Function to calculate ID value for every play
#

more_cleaning <- function() {
    # Only snatch every 10th frame (convert from 25fps to 2.5fps)
    stamps <- unique(s15$datetime2)[seq(1, length(unique(s15$datetime2)), by = 10)] 
    
    # Save stamps for later
    stampsSave <- data.frame(stamps)
    
    s15 <- filter(s15, datetime2 %in% stamps) %>% dplyr::arrange(event.id, datetime2, team, lastname)
    
    # Change ball to be it's own team
    s15$team <- as.character(s15$team)
    s15$team <- ifelse(is.na(s15$team) , 'ball', s15$team)
    
    s15$x <- s15$x_loc
    s15$y <- s15$y_loc
    s15$player <-  rep(c(paste0('a', 1:5), paste0('h', 1:5), 'ball') , times = round(nrow(s15)/11))[1:nrow(s15)]
    
    s15 <- s15 %>% arrange(player, datetime2)
    s15$stamp <- rep(1:length(stamps),times = 11)
    
    s15 <- s15 %>% 
           dplyr::group_by(player, lastname) %>% 
           dplyr::mutate(dist = sqrt( (x-lag(x)) ^ 2 + (y - lag(y)) ^ 2))
    
    if(unique(s15$ball_possession) == 'home') { 
        players <- c("ball", unique(s15[s15$team == 'home',]$lastname))
        players2 <- c(unique(s15[s15$team == 'away',]$lastname))
    }
    
    if(unique(s15$ball_possession) == 'away') { 
        players <- c("ball", unique(s15[s15$team == 'away',]$lastname))
        players2 <- c(unique(s15[s15$team == 'home',]$lastname))
    }
    
    s15$lastname <- factor(s15$lastname)
    
    colp <- brewer.pal(12, "Paired")[c(6, 2,8,2,2,2,8,2, 8,8,8)]

}

calculate_play <- function(i) {
    
    s15 <- select_id(all.movements = allm, id = ev[i]) 
    s15 <- filter(s15, action == table_fixing_clock[table_fixing_clock$event.id == ev[i],]$action)
    
    # Keep only the parts of the play that occur in the halfcourt

    # First half
    if(unique(s15$quarter) %in% c(1,2) ){
        if(unique(s15$ball_possession) == 'home') { 
              s15 <- filter(s15, datetime2 > min(filter(s15, lastname == 'ball', x_loc < 47)$datetime2))
        }
        if(unique(s15$ball_possession) == 'away') {
              s15 <- filter(s15, datetime2 > min(filter(s15, lastname == 'ball', x_loc > 47)$datetime2))
        }
    }
    
    #filter offensive court only
    if(unique(s15$quarter) %in% c(3,4) ){
        if(unique(s15$ball_possession) == 'home') { 
            s15 <- filter(s15, datetime2 > min(filter(s15, lastname == 'ball', x_loc > 47)$datetime2))
        }
      
        if(unique(s15$ball_possession) == 'away') {
            s15 <- filter(s15, datetime2 > min(filter(s15, lastname == 'ball', x_loc < 47)$datetime2))
        }
    }
    
    # Clean some more
    more_cleaning()
    
    # Generate gif of play
    P_180_2 <- ggplot(data=s15, aes(x=x_loc, y=-y_loc, group=lastname, col=lastname)) + 
           geom_polygon(data = rotate_court(court, theta = pi/2), aes(x = x, y = y, group = group), col = "gray") +
           coord_equal() +
           xlim(-2,96) +
           ylim(-55,2) +
           scale_x_continuous(breaks = c(0, 23.5, 47, 70.5, 94)) +
           scale_y_continuous(breaks = c(0, -12.5, -25, -37.5, -50)) +
           xlab("") + ylab("") +
           theme(axis.text.x = element_blank(),
                 axis.text.y = element_blank(), axis.ticks.x = element_blank(),
                 axis.ticks.y = element_blank(), axis.title = element_blank()
           ) 

    colp <- brewer.pal(12, "Paired")[c(6, 2,8,2,2,2,8,2, 8,8,8)]
    
    play_duration <- max(s15$shot_clock) - min(s15$shot_clock)
    
    P_TEST <- P_180_2 + 
              #geom_point(data = s15, aes(x_loc, -y_loc, group = lastname, col = lastname, shape = team), size =4 ) + 
              geom_path(data = s15, aes(x_loc, -y_loc, group = lastname, col = lastname), arrow = arrow(type = "closed", length = unit(0.03, "npc")), size = 0) +
              geom_text(data = s15, aes(x_loc, -y_loc+2, label = lastname, col = lastname), size = 2.5)+
              scale_color_manual(values = colp) +
              theme_bw() + 
              ggtitle(paste0('event_id = ', unique(s15$event.id))) 
    
    P_TEST_2 <- P_TEST + 
                transition_reveal(24-shot_clock) +
                exit_fade() + 
                shadow_wake(wake_length = 0.2)
    
    
    animate(P_TEST_2, nframes=length(s15), fps = 2.5, width = 1200, height = 800, renderer = gifski_renderer())
    anim_save(paste0("./nba_data/www/", 'event_id_', unique(s15$event.id), ".gif"))
    }



for (i in 1:length(ev)) {
    print(i)
    calculate_play(i)
}

```

## Clean main dataset further
```{r, eval = T}

stamps <- unique(allm$datetime2)[seq(1, length(unique(allm$datetime2)), by = 10)] 

# Save stamps for later
stampsSave <- data.frame(stamps)

player_path_for_play <- filter(allm, datetime2 %in% stamps) %>% dplyr::arrange(event.id, datetime2, team, lastname)

# Get player path function 
player_path_for_play <- player_path_for_play %>%
                        filter((event.id == 22))

#& ((lastname == "James") | (lastname == "ball"))) 

player_path_for_play$y_loc <- as.numeric(as.character(player_path_for_play$y_loc))
player_path_for_play$shot_clock <- as.numeric(as.character(player_path_for_play$shot_clock))

plot_temp <- P_180 +
             geom_path(data = player_path_for_play, aes(x_loc, -y_loc, group = lastname, col = lastname), arrow = arrow(type = "closed", length = unit(0.03, "npc")), size = 0) +
             #geom_text(data = player_path_for_play, aes(x_loc, -y_loc+2, label = lastname, col = lastname), size = 2.5)+
             theme_bw() + 
             ggtitle(paste0('event_id = ', unique(player_path_for_play$event.id))) +
             transition_reveal(24-shot_clock) +
             exit_fade() + 
             shadow_wake(wake_length = 0.2)
    
    
animate(plot_temp, nframes=73, fps = 2.5, width = 1200, height = 800, renderer = gifski_renderer())


plot(plot_temp)

```

## 
```{r, eval = T}


```

